CREATE TABLE IF NOT EXISTS usuarios(
    id_usuario INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    idade INTEGER NOT NULL,
    cpf VARCHAR(100) UNIQUE NOT NULL,
    numero VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS livros(
    id_livro INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL, 
    autor VARCHAR(100) NOT NULL,
    ano INTEGER NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS emprestimos(
    id_emprestimo INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usario INTEGER NOT NULL,
    id_livro INTEGER NOT NULL,

    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    FOREIGN KEY(id_livro) REFERENCES livros(id_livro)
);