def menu_principal():
    print('=' * 50)
    print(' ' * 14, 'Sistema De Biblioteca', ' ' * 20)
    print('=' * 50)
    print()
    print('1 - Livros')
    print('2 - Usuários')
    print('3 - Empréstimos')
    print('4 - Relatórios')
    print('0 - Sair')
    print()
    return int(input('Digite a seleção: '))

def menu_livros():
    print()
    print('1 - Cadastrar livro')
    print('2 - Remover livro')
    print('3 - Listar livros')
    print('4 - Ordenar livros por ano')
    print('5 - Ordernar livros por ordem alfabética')
    print('6 - Pesquisar pelo nome')
    print('0 - Voltar')
    print()
    return int(input('Digite a seleção: '))

def menu_usuarios():
    print()
    print('1 - Cadastrar usuário')
    print('2 - Remover usuário')
    print('3 - Listar usuários')
    print()
    return int(input('Digite a seleção: '))

def menu_acoes():
    print()
    print('1 - Emprestar livro')
    print('2 - Listar empréstimos')
    print('3 - Devolver livro')
    print('0 - Voltar')
    print()
    return int(input('Digite a ação requerida: '))

def menu_relatorio():
    print()
    print('=' * 20, 'RELATÓRIOS', '=' * 20)
    print()
    print('1 - Relatório de livros')
    print('2 - Relatório usuários')
    return int(input('Escolha uma opcao: '))

def menu_relatorio_livro():
    print()
    print('=' * 20, 'RELATÓRIOS LIVRO', '=' * 20)
    print()
    print('1 - Relatório padrão')
    print('2 - Relatório ordem alfabética ')
    print('3 - Relatório por ID')
    print('4 - Relatório dos usuários ')
    print('5 - Relatório por disponibilidade')
    print('6 - Relatório por indisponibilidade')
    print('7 - Voltar')
    print()
    return int(input('Informe o relatório desejado: '))

def menu_relatorio_usuario():
    print()
    print('=' * 20, 'RELATÓRIOS USUÁRIO', '=' * 20)
    print()
    print('1 - Relatório padrão')
    print('2 - Relatório em ordem alfabética ')
    print('3 - Relatório por ID')
    print('4 - Relatório por usuário com empréstimos')
    print('5 - Relatório por usuário e sem empréstimos')
    print('6 - Voltar')
    print()
    return int(input('Informe o relatório desejado: '))