
def menu_relatorio(self):
    print()
    print('=' * 20, 'RELATÓRIOS', '=' * 20)
    print()
    print('1 - Relatório de livros')
    print('2 - Relatório usuários')
    return int(input('Escolha uma opcao: '))

def menu_relatorio_livro(self):
    print()
    print('=' * 20, 'RELATÓRIOS LIVRO', '=' * 20)
    print()
    print('1 - Relatório padrão')
    print('2 - Relatório ordem alfabética ')
    print('3 - Relatório por ID')
    print('4 - Relatório dos usuários ')
    print('5 - Relatório por disponibilidade')
    print('6 - Relatório por indisponibilidade')
    print('7 - Voltar')
    print()
    return int(input('Informe o relatório desejado: '))

def menu_relatorio_usuario(self):
    print()
    print('=' * 20, 'RELATÓRIOS USUÁRIO', '=' * 20)
    print()
    print('1 - Relatório padrão')
    print('2 - Relatório em ordem alfabética ')
    print('3 - Relatório por ID')
    print('4 - Relatório por usuário com empréstimos')
    print('5 - Relatório por usuário e sem empréstimos')
    print('6 - Voltar')
    print()
    return int(input('Informe o relatório desejado: '))